version: '3.9'

services:
  nginx:
    container_name: nginx-server
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - docker-network
    # volumes:
      # - wordpress-volume:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb-server
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - docker-network
    # volumes:
      # - mariadb-volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress-server
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - docker-network
    # volumes:
      # - wordpress-volume:/var/www/html
    restart: always
    depends_on:
      - mariadb

networks:
  docker-network:
    driver: bridge

# volumes:
#   mariadb-volume:
#     driver: local
#   wordpress-volume:
#     driver: local